theme: jekyll-theme-minimal
title: Portfolio-Websites
description: A personal portfolio website designed to present my skills, projects, and professional details in a clean and structured manner. The site is fully responsive, built using HTML, CSS(Like transition, animation property, etc.)
